tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: first_link
            field:
              collections:
                - pages
              type: link
              display: 'First Link'
              icon: link
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: second_link
            field:
              collections:
                - pages
              type: link
              display: 'Second Link'
              icon: link
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: code_field
            field:
              theme: material
              mode: htmlmixed
              mode_selectable: true
              indent_type: tabs
              indent_size: 4
              key_map: default
              line_numbers: true
              line_wrapping: true
              antlers: false
              type: code
              display: 'Code Field'
              icon: code
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
